/*
    🔴 String Interpolation

        Swift uses string interpolation to include the name of a constant or variable as a placeholder in a longer string, and to prompt Swift to replace it with the current value of that constant or variable.
        Wrap the name in parentheses and escape it with a backslash before the opening parenthesis:

            print("The current value of friendlyWelcome is \(friendlyWelcome)")
*/